//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBFMobileKeyBag, SBFMobileKeyBagState;

@protocol SBFMobileKeyBagObserver <NSObject>

@optional
- (void)keybagDidFinishProcessingStateChange:(SBFMobileKeyBag *)arg1;
- (void)keybag:(SBFMobileKeyBag *)arg1 extendedStateDidChange:(SBFMobileKeyBagState *)arg2;
- (void)keybagWillBeginProcessingStateChange:(SBFMobileKeyBag *)arg1;
- (void)keybagDidUnlockForTheFirstTime:(SBFMobileKeyBag *)arg1;
@end

