//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDeviceApplicationScenePlaceholderContentContext.h"

@class NSString, NSURL;

@interface SBMutableDeviceApplicationScenePlaceholderContentContext : SBDeviceApplicationScenePlaceholderContentContext
{
}


// Remaining properties
@property(nonatomic) unsigned long long preferredContentType; // @dynamic preferredContentType;
@property(nonatomic) _Bool prefersLiveXIB; // @dynamic prefersLiveXIB;
@property(copy, nonatomic) NSString *requestedLaunchIdentifier; // @dynamic requestedLaunchIdentifier;
@property(copy, nonatomic) NSURL *url; // @dynamic url;
@end

